apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: prod
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
  type: ClusterIP